name: TESTS

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['5.4', '5.6']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libyaml-dev

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: intl, yaml #optional
        ini-values: "post_max_size=256M" #optional

    - name: Install YAML Extension
      run: |
        # 对于 PHP 5.4，需要手动编译
        if [ "${{ matrix.php-versions }}" == "5.4" ]; then
          # 安装编译所需工具
          sudo apt-get install -y php5-dev autoconf automake libtool

          # 下载 YAML 扩展源码
          git clone https://github.com/php/pecl-file_formats-yaml.git
          cd pecl-file_formats-yaml

          # 兼容 PHP 5.4 的版本
          git checkout yaml-1.3.0

          # 编译安装
          phpize
          ./configure
          make
          sudo make install

          # 启用扩展
          echo "extension=yaml.so" | sudo tee /etc/php/5.4/cli/conf.d/20-yaml.ini
        fi

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-versions }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test
      run: vendor/bin/phpunit tests/ConfigTest.php